# Generated by Django 4.1.7 on 2023-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mattress_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image')),
                ('Title', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Price', models.CharField(max_length=30)),
            ],
        ),
    ]
