# Generated by Django 4.1.7 on 2023-06-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MattressApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfSize', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='mattress_product',
            name='Discount',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='mattress_product',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='mattress_product',
            name='Size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MattressApp.size'),
        ),
    ]
