# Generated by Django 4.1.7 on 2023-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MattressApp', '0002_size_mattress_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattress_product',
            name='Discount',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
