# Generated by Django 4.1.7 on 2023-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MattressApp', '0004_alter_mattress_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonial_Mattress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=500)),
                ('Client_Image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
