# Generated by Django 4.1.7 on 2023-07-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MattressApp', '0005_testmonial_mattress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mattress_product',
            name='Size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
