# Generated by Django 4.1.7 on 2023-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0003_alter_product_card_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Client_Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images')),
                ('Facility_Name', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=500)),
                ('Client_Image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
