# Generated by Django 4.1.7 on 2023-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0004_client_rating_facility_testmonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_ProductButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
            ],
        ),
    ]
