# Generated by Django 4.1.7 on 2023-07-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0005_header_productbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_rating',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_category'),
        ),
        migrations.AddField(
            model_name='testmonial',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_category'),
        ),
    ]
