# Generated by Django 4.1.7 on 2023-07-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0006_client_rating_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='productCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_category'),
        ),
    ]
