# Generated by Django 4.1.7 on 2023-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0007_alter_product_card_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_card',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
    ]
