# Generated by Django 4.1.7 on 2023-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0008_product_card_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='Productprice',
            field=models.IntegerField(),
        ),
    ]
