# Generated by Django 4.1.7 on 2023-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0009_alter_product_card_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_card',
            name='Title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
