# Generated by Django 4.1.7 on 2023-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0010_product_card_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfSize', models.CharField(max_length=30)),
            ],
        ),
    ]
