# Generated by Django 4.1.7 on 2023-07-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0011_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_card',
            name='Size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productCategory.size'),
        ),
    ]
