# Generated by Django 4.1.7 on 2023-07-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0012_product_card_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_card',
            name='Size',
        ),
    ]
