# Generated by Django 4.1.7 on 2023-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0013_remove_product_card_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='TypeOfSize',
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
