# Generated by Django 4.1.7 on 2023-07-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCategory', '0014_remove_size_typeofsize_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_category'),
        ),
    ]
