# Generated by Django 4.1.7 on 2023-08-03 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productCategory', '0016_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_card')),
                ('Product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_category')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
