# Generated by Django 4.1.7 on 2023-08-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productCategory', '0017_buy_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('Shipping_Date', models.DateTimeField(auto_now_add=True)),
                ('Payment_Mode', models.CharField(max_length=50)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_card')),
                ('Product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productCategory.product_category')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Buy_Now',
        ),
    ]
