# Generated by Django 4.1.7 on 2023-08-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productCategory', '0018_order_user_detail_delete_buy_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='pincode',
            new_name='user_pincode',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='user',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
